site_name: Zen Cage 1.0.0 for Blender
site_description: Zen Cage 1.0.0 for Blender Documentation
nav:
    - Getting Started:
        - Introduction: index.md
        - Installation: installation.md
        - Cage Gizmo: cage_gizmo.md
    - Modules:
        - Align: align.md
        - Fit: fit.md
        - Distribute: distribute.md
        - Array: array.md
        - Clamp: fit.md
        - Rotate: rotate.md
        - Scale: scale.md
    - Additional:
        - Preferences: preferences.md
        - Help: help.md
        - Downloads: downloads.md
        - Changelog: changelog.md

docs_dir: mkdocs
site_dir: docs
theme: readthedocs

plugins:
   - glightbox

markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: 